# R2Devops.io pipeline template - this template aims to generate a complete pipeline
#
# Inputs:
#   - List of technologies detected in the project : css, html, markdown, python,

name: R2Devops
on:
  push:
    branches: [ master,r2devops-autopipeline]
  pull_request:
    branches: [ master ]

jobs:
# A style guide linter widely used
  python-flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - run: python -m pip install flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8

# A python formatter to help you write homogeneous code
  python-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable

